### ISSUE TITLE
Extends path does not work

### ISSUE THREAD

**Issue by mahish** [orcunsaltik/gulp-pug-3#2]
Thanks for the pug3 implementation. Im having difficiluties with extending templates. The following line `extends ../_layouts/archive.pug` in a `/Users/.../project/src/pug/some-page.pug` results in error:

```
Error: gulp-pug-3: Error: ENOENT: no such file or directory, open '/Users/.../project/src/_layouts/page.pug'
    at /Users/.../project/src/pug/pages/some-page.pug line 1
```

1. I do not extend `_layouts/page.pug` in `some-page.pug` but `_layouts/archive.pug` (it does not extends the page template neither)
2. the resulting path is wrong anyway (is `src/_layouts/page.pug` instead of `src/pug/_layouts/page.pug`)

Everything works with no problem using `gulp-pug` package

Any idea?

**Comment by philmayfield** [comment]
Agreed, much appreciated @orcunsaltik!  I noticed the same with some uses of `extends` and `include`.  Switching those to use absolute paths along with a defined `basedir` in the options fixed them for me.  Quite odd, but it got me past the blocker and using Pug 3.

**Comment by mattpr** [comment]
This is definitely a bug due to config reuse/modification across multiple input files from gulp.  I've opened a pull request.

This also results in reports of wrong file (first pug file processed) reported as having an error even though it doesn't because pug is told to use the same filename (by gulp-pug-3) for all input files.

If you fix this or merge the PR, it would be great if we could get a new release published to npm so I don't need to keep maintaining my fork.

This bug definitely breaks people moving from pug2 -> 3 that had working builds with pug2.
